-- Staging model for SEC derivative transaction data
-- Excludes REMARKS, AFF10B5ONE, and columns ending with _FN as requested

WITH source AS (
    SELECT * 
    FROM {{ source('insider_transactions', 'sec_deriv_trans') }}
),

renamed AS (
    SELECT
        ACCESSION_NUMBER,
        DERIV_TRANS_SK,
        SECURITY_TITLE,
        SAFE_CAST(TRANS_DATE AS DATE) as TRANSACTION_DATE,
        SAFE_CAST(DEEMED_EXECUTION_DATE AS DATE) as DEEMED_EXECUTION_DATE,
        TRANS_FORM_TYPE as FORM_TYPE,
        TRANS_CODE as TRANSACTION_CODING_CODE,
        TRANS_ACQUIRED_DISP_CD as TRANSACTION_ACQUIRED_DISPOSED_CODE,
        TRANS_SHARES as TRANSACTION_SHARES,
        TRANS_PRICEPERSHARE as TRANSACTION_PRICE_PER_SHARE,
        SHRS_OWND_FOLWNG_TRANS as SHARES_OWNED_FOLLOWING_TRANSACTION,
        VALU_OWND_FOLWNG_TRANS as VALUE_OWNED_FOLLOWING_TRANSACTION,
        DIRECT_INDIRECT_OWNERSHIP,
        NATURE_OF_OWNERSHIP,
        EQUITY_SWAP_INVOLVED,
        TRANS_TIMELINESS as TRANSACTION_TIMING_CODE,
        CONV_EXERCISE_PRICE as EXERCISE_PRICE,
        CAST(EXCERCISE_DATE AS DATE) as EXERCISE_DATE,
        CAST(EXPIRATION_DATE AS DATE) as EXPIRATION_DATE,
        UNDLYNG_SEC_TITLE as UNDERLYING_SECURITY_TITLE,
        UNDLYNG_SEC_SHARES as UNDERLYING_SECURITY_SHARES,
        UNDLYNG_SEC_VALUE as UNDERLYING_SECURITY_VALUE
    FROM source
    WHERE 1=1
    -- Exclude columns ending with _FN and _sdc metadata columns
)

SELECT * FROM renamed
