-- Line-level fact: one row per non-derivative SEC transaction line (accession + NONDERIV_TRANS_SK).

WITH source AS (
    SELECT *
    FROM {{ source('insider_transactions', 'sec_nonderiv_trans') }}
),

renamed AS (
    SELECT
        ACCESSION_NUMBER,
        NONDERIV_TRANS_SK,
        SECURITY_TITLE,
        SAFE_CAST(TRANS_DATE AS DATE) AS TRANSACTION_DATE,
        SAFE_CAST(DEEMED_EXECUTION_DATE AS DATE) AS DEEMED_EXECUTION_DATE,
        TRANS_FORM_TYPE AS FORM_TYPE,
        TRANS_CODE AS TRANSACTION_CODING_CODE,
        TRANS_ACQUIRED_DISP_CD AS TRANSACTION_ACQUIRED_DISPOSED_CODE,
        TRANS_SHARES AS TRANSACTION_SHARES,
        TRANS_PRICEPERSHARE AS TRANSACTION_PRICE_PER_SHARE,
        SHRS_OWND_FOLWNG_TRANS AS SHARES_OWNED_FOLLOWING_TRANSACTION,
        VALU_OWND_FOLWNG_TRANS AS VALUE_OWNED_FOLLOWING_TRANSACTION,
        DIRECT_INDIRECT_OWNERSHIP,
        NATURE_OF_OWNERSHIP,
        EQUITY_SWAP_INVOLVED,
        TRANS_TIMELINESS AS TRANSACTION_TIMING_CODE
    FROM source
    WHERE 1 = 1
)

SELECT * FROM renamed
